In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("spotify_millsongdata.csv")

In [3]:
df.head(5)

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [4]:
df.tail(5)

,artist,song,link,text
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [5]:
df.shape

(57650, 4)

In [6]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [7]:
df =df.sample(10000).drop('link', axis=1).reset_index(drop=True)

In [8]:
df.head(10)

,artist,song,text
0,George Harrison,You,"You \r\nGeorge Harrison \r\n \r\n(one, two,..."
1,Outkast,Intro,"O-U-T-K-A-S-T \r\nLive, from the center of th..."
2,Korn,Slept So Long,"Walking, waiting \r\nAlone without a care \r..."
3,Selah,"Wonderful, Merciful Savior","Verse 1 \r\nWonderful, merciful Savior \r\nP..."
4,Bosson,Rockstar,"He's a kid, with a dream \r\nBut he's differe..."
5,Cat Stevens,Jzero,"Well I ain't got nothing, \r\nBut it don't wo..."
6,Metallica,One (Rare),The cerebrum has suffered massive and reparabl...
7,Queen Latifah,Turn You On,Did I make you hot? Tell me \r\n \r\nI didn'...
8,Kinks,Holiday,"Holiday, \r\nOh what a lovely day today, \r\..."
9,Travis,The Last Laugh Of The Laughter,When the laughter fade away \r\nMa vie \r\nT...

In [9]:
df['text'][0]

"You  \r\nGeorge Harrison  \r\n  \r\n(one, two,  \r\nOne, two, three, four)  \r\n  \r\nI, I love, love  \r\nAnd I, and I love you  \r\nOh you, you, yeah you  \r\n  \r\nAnd you, you, love, love  \r\nAnd you, yes you, you love me  \r\nYeah you, you, yeah you  \r\n  \r\nAnd when I'm holding you  \r\nWhat a feeling  \r\nSeems so good to be true  \r\nThat I'm telling you all  \r\nThat I must be dreaming  \r\n  \r\nAnd I, and I, I love you  \r\nOh you, oh you, yeah you  \r\n  \r\nAnd when I'm holding you  \r\nWhat a feeling  \r\nSeems so good to be true  \r\nThat I'm telling you all  \r\nThat I must be dreaming  \r\n  \r\nNow I, oh I, I love, love  \r\nAnd I, yeah I, I love you, I love you  \r\nOh you, you, oh you  \r\n  \r\nOh, you know that I love you, oh oh oh  \r\nOh, you know that I love you, I love you, I, I said I love you\r\n\r\n"

In [10]:
df.shape

(10000, 3)

Text Cleaning/ Text Preprocessing

In [11]:
df['text'] = df['text'].str.lower().replace(r'^\w\s', ' ').replace(r'\n', ' ', regex = True)

In [12]:
import nltk
nltk.download('punkt_tab')
nltk.download('punkt')

from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()

def tokenization(txt):
    tokens = nltk.word_tokenize(txt)
    stemming = [stemmer.stem(w) for w in tokens]
    return " ".join(stemming)

[nltk_data] Downloading package punkt_tab to /Users/user/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt to /Users/user/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
df['text'] = df['text'].apply(lambda x: tokenization(x))

In [14]:
	
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
tfidvector = TfidfVectorizer(analyzer='word',stop_words='english')
matrix = tfidvector.fit_transform(df['text'])
similarity = cosine_similarity(matrix)

In [ ]:
similarity[0]

In [ ]:
df[df['song'] == 'Obvious']

In [ ]:
def recommendation(song_df):
    idx = df[df['song'] == song_df].index[0]
    distances = sorted(list(enumerate(similarity[idx])),reverse=True,key=lambda x:x[1])
    
    songs = []
    for m_id in distances[1:21]:
        songs.append(df.iloc[m_id[0]].song)
        
    return songs

In [ ]:
recommendation('Obvious')

In [ ]:
import pickle
pickle.dump(similarity,open('similarity.pkl','wb'))
pickle.dump(df,open('df.pkl','wb'))